### ISSUE TITLE
Support for CircleCI Enterprise

### ISSUE THREAD

**Issue by iserko** [nolaneo/SeaEye#5]
CircleCI is starting to roll out their Enterprise solutions and it would be great if the app would expose the URL setting so that you could point it towards CircleCI Enterprise

**Comment by nolaneo** [comment]
Hey @iserko, is it just the base URL `https://circleci.com/api/v1/` that you need to change? I can't find any docs on circle's site around how Enterprise edition and their API work together.

If it's just the base URL then that should be easy enough to expose.

**Comment by ndintenfass** [comment]
Yes, the base URL should be sufficient to expose to work with CircleCI Enterprise.

**Comment by nolaneo** [comment]
OK cool, I'll cut a branch this weekend with that ability.
